services: 
  postgres:
    container_name: wishlist
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wish-list
      PDDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres